BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE COLLABORATION_COOPERATION_BPMN_NODE REUSE STORAGE';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE COLLABORATION_COOPERATION_BPMN_NODE_SEQ RESTART START WITH 1';
END;