BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE COLLABORATION_COOPERATION_NODE_CONVERSATION REUSE STORAGE';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE COLLABORATION_COOPERATION_NODE_CONVERSATION_SEQ RESTART START WITH 1';
END;