BEGIN
    EXECUTE IMMEDIATE 'TRUNCATE TABLE COLLABORATION_COOPERATION_RES_ASSOCIATION REUSE STORAGE';
    EXECUTE IMMEDIATE 'ALTER SEQUENCE COLLABORATION_COOPERATION_RES_ASSOCIATION_SEQ RESTART START WITH 1';
END;